### ISSUE TITLE
MX922 scanner not detected

### ISSUE THREAD

**Issue by sharadmittal** [Ordissimo/scangearmp2#10]
I followed the instructions at http://ubuntuhandbook.org/index.php/2018/10/canon-ij-printer-scangear-mp-drivers-ubuntu-18-04-18-10/

Used scangearmp-mx920 
Everything installed

scangearmp2 says "Internal error occured. The scanner driver will be closed".

Any ideas?

**Comment by sharadmittal** [comment]
xsane does connect with the scanner but fails to scan from ADF properly... throws error in the middle of scanning a page.  Saw an error on console - "[bjnp] bjnp_recv_data: ERROR - could not read response payload (select timed out after 1000 ms)!"

**Comment by Ordissimo** [comment]
Hello,
You are not on the right track.
Indeed the MX-922 uses scangearmp-mx920.
To use it you have to run the command: scnagearmp and no scanbgearmp2

**Comment by sharadmittal** [comment]
Thank you for your reply. Does your PPA (https://launchpad.net/~thierry-f/+archive/ubuntu/fork-michael-gruz) have a package for this version of scangearmp or should I compile it myself? I think I tried the scangearmp from that PPA - and it did not find the scanner.

**Comment by Ordissimo** [comment]
I want to help you, but you must be in the right line.
https://github.com/Ordissimo/scangearmp
thank you

**Comment by sharadmittal** [comment]
Thanks - I have opened the issue in https://github.com/Ordissimo/scangearmp
