### ISSUE TITLE
scanning  portion of A4 paper

### ISSUE THREAD

**Issue by ArgonCooper** [Ordissimo/scangearmp2#11]
Hi,

With your version of scangearmp2, I can detect my Canon TS8151 scanner (via WIFI) and use it with Xsane or SimpleScan. However, I can only scan a full A4 paper with xsane (with my previous scanner, I could select a part of the scanning area and only scan this particular part).

Is it a bug or something you haven't yet implemented? (if so, do you plan to implement it?) 

Thank you anyway, I couldn't scan anything without you!

**Comment by Ordissimo** [comment]
Canon does not give me access to this type of setting.
Merci
