### ISSUE TITLE
Add scangearmp2.desc

### ISSUE THREAD

**Issue by paddy-hack** [Ordissimo/scangearmp2#12]
The SANE Project provides information on scanner support status for third-party (external) backends in a simple plain text format and publishes that on [the project's website](http://sane-project.org/).  Many people look at the [lists](http://sane-project.org/sane-supported-devices.html) there to see if their device is supported.

I was wondering if this project could provide a `scangearmp2.desc` file so that I, as self-appointed SANE Project Janitor, could add it to the [list of external backends](http://sane-project.org/lists/sane-backends-external.html).  The file format is documented in [`doc/descriptions.txt`](https://gitlab.com/sane-project/backends/blob/master/doc/descriptions.txt).

**Comment by Ordissimo** [comment]
It's a very good idea.

**Comment by Ordissimo** [comment]
I added the list of devices supported by scangeamp2 in the sane-backends project.
[#227](https://gitlab.com/sane-project/backends/merge_requests/227)
