### ISSUE TITLE
ARM / Raspberry Pi support

### ISSUE THREAD

**Issue by alaxxel** [Ordissimo/scangearmp2#13]
Hi, and thank you for this project !

I would like to make my scanner work on a Raspberry Pi 3. When I follow the instructions in the README I get the following error:

> /usr/bin/ld: skipping incompatible /tmp/scangearmp2/scangearmp2/../com/libs_bin32/libcncpmslld2.so when searching for -lcncpmslld2
> ../../com/libs_bin64/libcncpmslld2.so: file not recognized: File format not recognized

I'm guessing it's because the architecture of these *.so files isn't ARM-compatible. I Google-searched for an ARM version of these files but did not find anything.

Am I missing something? How can I help make it work? I'd settle for a quick and dirty solution (could something like qemu help?) but I'm willing to help find and document a proper one!

EDIT : if it helps, my printer / scanner is a TS6150

**Comment by Ordissimo** [comment]
Hello,
Your scanner (in USB) is now managed by sane.
I use the piloted proprio, canon does not provide a driver for ARM.

**Comment by kno10** [comment]
The python script at https://github.com/kno10/python-scan-eSCL should work fine on Raspi, too.
It does not rely on binary blobs, but rather access the scanner via HTTP.
