### ISSUE TITLE
TS5055 not detected by sane - scangearmp2 sees it well

### ISSUE THREAD

**Issue by shooash** [Ordissimo/scangearmp2#14]
Hi!
I have problems trying to detect TS5055 pixma scanner via wifi. I've built and installed the canon_pixma without problems, added it to /etc/sane.d/dll.conf
I still cannot see the scanner with scanimage -L It's detected only by scangearmp2 tool.
Is there any way to debug the backend or to set it check chosen ip/mac?

> cat /etc/sane.d/dll.conf
> # dll.conf - Configuration file for the SANE dynamic backend loader
> #
> # Backends can also be enabled by configuration snippets under the dll.d/
> # directory -- third party backends can drop their configuration file in
> # this in this directory, named after the backend.
> #
> # The next line enables the network backend; comment it out if you don't
> # need to use a remote SANE scanner over the network -- see sane-net(5)
> # and saned(8) for details.
> #net
> abaton
> agfafocus
> #apple
> avision
> artec
> artec_eplus48u
> as6e
> bh
> canon
> #canon630u
> #canon_dr
> #canon_pp
> cardscan
> coolscan
> #coolscan2
> coolscan3
> #dc25
> #dc210
> #dc240
> dell1600n_net
> dmc
> epjitsu
> #epson
> epson2
> epsonds
> fujitsu
> #gphoto2
> genesys
> gt68xx
> hp
> hp3900
> hpsj5s
> hp3500
> hp4200
> hp5400
> hp5590
> hpljm1005
> hs2p
> ibm
> kodak
> kodakaio
> kvs1025
> kvs20xx
> leo
> lexmark
> ma1509
> magicolor
> matsushita
> microtek
> microtek2
> mustek
> #mustek_pp
> mustek_usb
> mustek_usb2
> nec
> niash
> #p5
> pie
> pint
> pixma
> plustek
> #plustek_pp
> #pnm
> qcam
> ricoh
> rts8891
> s9036
> sceptre
> sharp
> sm3600
> sm3840
> snapscan
> sp15c
> #st400
> #stv680
> tamarack
> teco1
> teco2
> teco3
> #test
> u12
> umax
> #umax_pp
> umax1220u
> v4l
> xerox_mfp
> 
> canon_pixma
> 
> scanimage -L
> 
> No scanners were identified. If you were expecting something different,
> check that the scanner is plugged in, turned on and detected by the
> sane-find-scanner tool (if appropriate). Please read the documentation
> which came with this software (README, FAQ, manpages).
> 
>

**Comment by xiaomengxinyo** [comment]
@shooash Hi! Can the author update XHFw3? Android 8 and above really want to use XHFw3. I really appreciate your contribution.

**Comment by Ordissimo** [comment]
Hello,
You do not give enough detail.
Your OS?

**Comment by xiaomengxinyo** [comment]
@Ordissimo XHFw3 does not fully support Android 7 and above, but also I have some BUGs. Activation module will lead to the failure to install applications, resulting in system instability (Redmi 5Plus MIUI8.11.2 Android 7.12). I hope that after updating, I can fully support Android 7 and above, and repair some BUGs.

**Comment by Ordissimo** [comment]
Sorry,
I do not have the lib available for android, watched with a chroot.

**Comment by xiaomengxinyo** [comment]
@Ordissimo Well, thank you very much.

**Comment by xiaomengxinyo** [comment]
@shooash  BUG I know at present (or BUG I've seen): Some functions may fail at any time, some system applications may flip (millet video, application package management components, etc.) and some BUG (Redmi 5 Plus Android 7.12 MIUI 8.11.2) that I haven't found yet. Thank you very much.
