### ISSUE TITLE
Fedora 30 Install Invalid argument

### ISSUE THREAD

**Issue by MelchiorIm3Tal** [Ordissimo/scangearmp2#18]
This happens:
$ sudo dpkg -iG ./packages/scangearmp2_3.40-1_amd64.deb
Vormals nicht ausgewähltes Paket scangearmp2 wird gewählt.
(Lese Datenbank ... 19 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../scangearmp2_3.40-1_amd64.deb ...
Entpacken von scangearmp2 (3.40-1) über (3.40-1) ...
dpkg (Unterprozess): Security-Ausführungskontext für Betreuerskript kann nicht gesetzt werden: Invalid argument
dpkg: Warnung: Unterprozess altes post-removal-Skript gab den Fehlerwert 2 zurück
dpkg: stattdessen wird Skript aus dem neuen Paket probiert ...
dpkg (Unterprozess): Security-Ausführungskontext für Betreuerskript kann nicht gesetzt werden: Invalid argument
dpkg: Fehler beim Bearbeiten des Archivs ./packages/scangearmp2_3.40-1_amd64.deb (--install):
 Unterprozess neues post-removal-Skript gab den Fehlerwert 2 zurück
dpkg (Unterprozess): Security-Ausführungskontext für Betreuerskript kann nicht gesetzt werden: Invalid argument
dpkg: Fehler beim Aufräumen:
Unterprozess neues post-removal-Skript gab den Fehlerwert 2 zurück
Fehler traten auf beim Bearbeiten von:
 ./packages/scangearmp2_3.40-1_amd64.deb

Any Hint available?

**Comment by Ordissimo** [comment]
We are at version 3.70 of the package.
For simplicity, I advise you to orient yourself towards the project we have chosen.
I spent last weekend for CentOS.
Follow the readme. https://github.com/Ordissimo/libmfp2-canon
