### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by TurboBlaze** [Ordissimo/scangearmp2#19]
Please update Russian localization (look at my attach) or download my ru.po file http://www.mediafire.com/file/1qn59d64givrhs3/ru.po/file
[ru.po.zip](https://github.com/Ordissimo/scangearmp2/files/3828318/ru.po.zip)
Thanks.

**Comment by Ordissimo** [comment]
Translation added.
We are working on an alternative to scangearmp2.
Watch :https://gitlab.com/sane-escl/sane-escl
