### ISSUE TITLE
Change default Paper Size

### ISSUE THREAD

**Issue by decadenza** [Ordissimo/scangearmp2#2]
There's no way to configure default options? I'd like to set "A4" as default Paper Size.

**Comment by Ordissimo** [comment]
Hi,
The sane backend does not allow you to record your preferences.
You can save your preferences with xsane.
The options managed by the backend are:
1) the quality
2) the color
3) output format, JPG, PNG, PPM or ...
I should be able to add the paper size option. I set the A4 as the default preference.
