### ISSUE TITLE
Scan from ADF using scanimage?

### ISSUE THREAD

**Issue by bastianbeischer** [Ordissimo/scangearmp2#26]
Hey,

This maybe more of a question, than a bug report: I have a network attached Canon Pixma TR8550 printer, which has an automatic document feeder (ADF). Using the scangearmp2 binary I can scan from the ADF  in simplex mode and that works. But I would like to do it from the "scanimage" command line interface. However I can't find a command line option for that. Also I'm not sure if the canon_pixma sane backend even is used, since the printer works out of the box (i.e. without scangearmp2 and/or the "canon_pixma" sane backend installed) using ESCL. scanimage -L lists:

```
device `escl:https://192.168.179.103:443' is a ESCL Canon TR8500 series flatbed scanner
device `escl:http://192.168.179.103:80' is a ESCL Canon TR8500 series flatbed scanner
device `canon_pixma:34-9F-7B-1F-43-BB' is a CANON TR8500 series flatbed scanner
```

But no matter which device I choose I don't see an option to make it scan from the ADF in scanimage -d canon_pixma:34-9F-7B-1F-43-BB -A:

```
All options specific to device `canon_pixma:34-9F-7B-1F-43-BB':
  Scan Mode:
    --mode Color|Gray [Color]
        Selects the scan mode (e.g., lineart, monochrome, or color).
    --resolution 75|100|150|200|300dpi [300]
        Sets the resolution of the scanned image.
    --preview[=(yes|no)] [no]
        Request a preview-quality scan.
  Geometry:
    -l 0..0.00457764pel (in steps of 1.52588e-05) [0]
        Top-left x position of scan area.
    -t 0..0.00457764pel (in steps of 1.52588e-05) [0]
        Top-left y position of scan area.
    -x 0..0.00457764pel (in steps of 1.52588e-05) [0.0378418]
        Width of scan-area.
    -y 0..0.00457764pel (in steps of 1.52588e-05) [0.0535126]
        Height of scan-area.
```

I feel like there might be the possibility to make this work, given that the scangearmp2 GUI binary provides the ADF scan as an option? Am I doing something wrong?

**Comment by Ordissimo** [comment]
I didn't implement ADF mode for scanning. It won't work.
But there are solutions. What is your OS (version)?

**Comment by bastianbeischer** [comment]
I am on Arch Linux (which is a rolling release distro), this means sane 1.0.29 at the moment. I compiled the code from this repository manually and added the plugin to /usr/lib/sane, also added "canon_pixma" to /etc/sane.d/dll.conf.

Would it be theoretically possible to implement ADF or are there problems which can't be overcome?

**Comment by Ordissimo** [comment]
For the adf you can use scanadf which belongs to the sane package.
I suggest you update sane-backends. The eSCL driver now supports ADF. 
I could but it doesn't make sense.

**Comment by bastianbeischer** [comment]
Thanks, I was able to achieve what I want with the sane-airscan driver.

**Comment by Ordissimo** [comment]
Great!
