### ISSUE TITLE
I can't compile in RaspberryPI 3+

### ISSUE THREAD

**Issue by joseantoniosa** [Ordissimo/scangearmp2#28]
I've tried to compile your excellent work in raspberrypi 
Linux gutenberg 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
But your code depends on  "libcncpmslld2.so, libcncpnet20.so , libcncpnet2.so,   libcncpnet30.so," binary only libraries. Is these source code public available? Thank you in advance!

Best regards!
José A. Salgueiro

**Comment by Ordissimo** [comment]
Excuse me, I didn't receive the notification!
Indeed you can't builder for arm, I rely on canon binary that doesn't provide source code !
