### ISSUE TITLE
Scanner not detected on openSUSE Leap

### ISSUE THREAD

**Issue by femartini** [Ordissimo/scangearmp2#29]
Hello,
I packaged v3.90 for openSUSE Leap 15.2 and the stand alone program works, but the scanner detection fails.
The printer is a Canon pixma TS8151, USB ID 04a9:1821: is scangearmp2 supposed to detect it? If so, under what
name?

Also is there anything else I should check?

Thanks

**Comment by Ordissimo** [comment]
Excuse me, I didn't receive the notification!
I advise you to have a look at the [fix](https://github.com/Ordissimo/scangearmp2/pull/27/files) I just applied, there is a good chance that it will solve your problem.

**Comment by femartini** [comment]
Thanks for your reply.

I tried again with the fix above and now the scanner is finally detected, only I can't actually configure it under YaST and actually use it :cry: 

I had to tinker a bit with the [spec file](https://github.com/Ordissimo/scangearmp2/files/5265935/scangearmp2.spec.gz) to make it palatable to the OBS build system, I hope I didn't mess up anything. Otherwise do you recommend a local build via rpmbuild?

**Comment by Ordissimo** [comment]
Hi,
I updated the backend to scangearmp2 4.10, and added support for new options.
Can you tell me if this solves your problem?

**Comment by Ordissimo** [comment]
I close the ticket, there were some packagind problems.
This is solved! 
I don't know much about RPM systems, if you have time to propose me a new packaging, I'm a taker!
