### ISSUE TITLE
cannot compile on arm32

### ISSUE THREAD

**Issue by akamming** [Ordissimo/scangearmp2#30]
Hi,

i tried to build the package on a rpi4 with 32-bit pi os (armhf).

This led to the following error:
`/usr/bin/ld: skipping incompatible /home/pi/dev/scangearmp2/scangearmp2/../com/libs_bin32/libcncpmslld2.so when searching for -lcncpmslld2
/usr/bin/ld: cannot find -lcncpmslld2
/usr/bin/ld: skipping incompatible /home/pi/dev/scangearmp2/scangearmp2/../com/libs_bin32/libcncpnet2.so when searching for -lcncpnet2
/usr/bin/ld: cannot find -lcncpnet2
/usr/bin/ld: skipping incompatible /home/pi/dev/scangearmp2/scangearmp2/../com/libs_bin32/libcncpnet20.so when searching for -lcncpnet20
/usr/bin/ld: cannot find -lcncpnet20
/usr/bin/ld: skipping incompatible /home/pi/dev/scangearmp2/scangearmp2/../com/libs_bin32/libcncpnet30.so when searching for -lcncpnet30
/usr/bin/ld: cannot find -lcncpnet30
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:569: scangearmp2] Fout 1
make[3]: Map '/home/pi/dev/scangearmp2/scangearmp2/src' wordt verlaten
make[2]: *** [Makefile:425: all-recursive] Fout 1
make[2]: Map '/home/pi/dev/scangearmp2/scangearmp2' wordt verlaten
make[1]: *** [Makefile:357: all] Fout 2
make[1]: Map '/home/pi/dev/scangearmp2/scangearmp2' wordt verlaten
make: *** [debian/rules:46: build-stamp] Fout 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2`

**Comment by Ordissimo** [comment]
I base myself on the pilot owner of Canon. Only i386 and amd64 support is provided by Canon. It is not possible to build the driver for other architectures. 
For which device do you need this driver?

**Comment by akamming** [comment]
Raspberry pi.

Although in the meantime 8 found an alternate solution (compiling the latest sane backend which supports airscan and so also my  ts5351)

**Comment by Ordissimo** [comment]
Okay, I'm closing your ticket.
