### ISSUE TITLE
Installing under MX Linux

### ISSUE THREAD

**Issue by FlorianR420** [Ordissimo/scangearmp2#38]
Hey, I tried to install this under MX Linux 19.3 to get my Canon Scanner (TR8550) to work in Wifi. Everything works fine until the last command '(sudo) apt install ../scangearmp2_4.12-1_amd64.deb'. I get the error 'Unsupported file ../scangearmp2_4.12-1_amd64.deb given on commandline'. Any hints for a newbie? As said, everything up to that point looks fine. Thanks!

**Comment by Ordissimo** [comment]
Hi @FlorianR420,
Can you test this : 
```
sudo dpkg -i ../scangearmp2_4.12-1_amd64.deb
```

**Comment by FlorianR420** [comment]
Hi @Ordissimo, THANKS, I got it kinda working. 
What I did: 
I had to leave out the "-1" from the filename. 
Also, I had to switch off my firewall completely. I'm not using firewalld therefore the commands proposed didn't work, but that's ok, I can switch it on again after scanning.
Now I can scan, only from the platen unfortunately, with Simple Scan (default scanner app on MX Linux). 
Scangearmp2 app itself doesn't work anymore, it says "internal error" or something like that, but who cares.
Scanning from the feeder doesn't work for now.

**Comment by Ordissimo** [comment]
Hi @FlorianR420,
Can you tell me how you did it (the link if you want, maybe something is not up to date)?

**Comment by FlorianR420** [comment]
I followed the installation instructions for Debian-based systems precisely, I just inserted your recommended command 'sudo dpkg -i ../scangearmp2_4.12-1_amd64.deb' before the 'apt install ../scangearmp2_4.12-1_amd64.deb' command. For it to work, I had to type 'scangearmp2_4.12_amd64.deb' instead of 'scangearmp2_4.12**-1**_amd64.deb', as I saw that the file was named without the **-1** in my folder (downloaded via the 'git clone' command as in the instructions. Maybe you or another author changed the name of the file during some work on the repository?)

With regards to my firewall, I am using UFW (**u**ncomplicated **f**ire**w**all), a simple frontend for iptables. It was preinstalled on my distro and I'm just using the default settings for now.

Feel free to keep me posted if this helps you to further develop the driver or you think I did something wrong during installation of it. I think it's a great tool. I'm just starting my degree in computer science, but am very interested in open source software.

Kind Regards
Florian

**Comment by Ordissimo** [comment]
Could you test to install the package prepared on this link : 
[sangearmp2](https://github.com/Ordissimo/scangearmp2/releases/tag/4.12)
MX-Linux 19.3 is based on buster.
Can you install the corresponding package.
and redo your tests.
Thanks

**Comment by Ordissimo** [comment]
I made some correction, can you test with the new package and give me a feedback?
New version [v4.12.1](https://github.com/Ordissimo/scangearmp2/releases/tag/v4.12.1)

**Comment by FlorianR420** [comment]
Hi, so after installing the first package, nothing changed and I can't install the second (v4.12.1), because the *amd64.deb file is missing in the repository. (The dbgsym is there but not the dependency.)

**Comment by Ordissimo** [comment]
Sorry, fixed !

**Comment by FlorianR420** [comment]
Hey, first of all, thank you again! It works now from Wifi. But the feeder still doesn't work, only the flatbed. If I try to scan from feeder, he simply scans from flatbed. But big improvement to be able to scan from Wifi at all! Nice!

**Comment by Ordissimo** [comment]
Hi @FlorianR420,
ADF and ADF Duplex works => https://github.com/Ordissimo/scangearmp2/releases/tag/4.20.1
