### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by KieranFitz3** [Ordissimo/scangearmp2#4]
Would like to use the backend on UBUNTU 14.04 64 bit with my new PIXMA TS5050 Scanner
The debian install fails at the build stage with the following output.
Any idea what I'm doing wrong?

kieran@Desktop:~$ cd scangearmp2
kieran@Desktop:~/scangearmp2$ debuild -tc
 dpkg-buildpackage -rfakeroot -D -us -uc -tc
dpkg-buildpackage: source package scangearmp2
dpkg-buildpackage: source version 3.50-2ubuntu.artful
dpkg-buildpackage: source distribution stable
dpkg-buildpackage: source changed by thierry <thierry@thierry-ThinkPad>  (??????????)
 dpkg-source --before-build scangearmp2
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: libusb-1.0-0-dev libtool-bin | libtool libjpeg-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -tc failed
kieran@Desktop:~/scangearmp2$_

**Comment by Ordissimo** [comment]
Hi,
There are missing translations:
kieran@Desktop: /scangearmp2$ sudo apt-get install libusb-1.0-0-dev libtool-bin libjpeg-dev
or (If the previous installation failed)
kieran@Desktop: /scangearmp2$ sudo apt-get install libusb-1.0-0-dev libtool libjpeg-dev
kieran@Desktop: /scangearmp2$ debuild -tc

Ignore the signature, you do not have to create or modify the package. That should do it, thank you for confirming me.

**Comment by Ordissimo** [comment]
thierry@thierry-ThinkPad : It's me.
