### ISSUE TITLE
Installing under arm64

### ISSUE THREAD

**Issue by mahmouddaif** [Ordissimo/scangearmp2#40]
Hello I am currently trying to install this software on a jetson xavier machine using  arm64 architecture and I get the following error when execting "dpkg-buildpackage -us -uc" can you help me with that please?
`dpkg-buildpackage: info: source package scangearmp2
dpkg-buildpackage: info: source version 4.12
dpkg-buildpackage: info: source distribution buster
dpkg-buildpackage: info: source changed by thierry <thierry@ordissimo.com>
dpkg-buildpackage: info: host architecture arm64
 dpkg-source --before-build scangearmp2
 fakeroot debian/rules clean
dh clean
 dpkg-source -b scangearmp2
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building scangearmp2 in scangearmp2_4.12.tar.xz
dpkg-source: info: building scangearmp2 in scangearmp2_4.12.dsc
 debian/rules build
dh build
 fakeroot debian/rules binary
dh binary
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning:     debian/changelog(l11): ignoring invalid week day 'tue'
LINE:  -- thierry <thierry@thierry-thinkpad>  tue, 05 dec 2017 21:03:04 +0100
dpkg-genbuildinfo: error: binary build with no binary artifacts found; .buildinfo is meaningless
dpkg-buildpackage: error: dpkg-genbuildinfo subprocess returned exit status 2
`

**Comment by Ordissimo** [comment]
Can you tell me what is your device, brand and model?

**Comment by mahmouddaif** [comment]
Thank you for your reply, I use similar device to this running jetson pack 4.5
https://developer.nvidia.com/embedded/jetson-agx-xavier-developer-kit

**Comment by Ordissimo** [comment]
Sorry, your printer ?

**Comment by mahmouddaif** [comment]
Thank you, I use canoscan lide 400.

**Comment by Ordissimo** [comment]
Can you give me the usbid?
```
lsusb
```

**Comment by mahmouddaif** [comment]
Sure, here you go. 
`Bus 001 Device 006: ID 04a9:1912 Canon, Inc. 
`

**Comment by Ordissimo** [comment]
Perfect!
scangearmp2 works only on i386 and amd64 architecture.
The info you just gave me shows that your driver is supported by [sane-backends](https://gitlab.com/search?search=lide%20400&project_id=429008&group_id=251139)!
Your libsane version is too old, update to [1.0.31](https://packages.debian.org/fr/sid/libsane) if possible.
I'm not here (I'm going to the dentist) but I can help you afterwards, if you need !

**Comment by mahmouddaif** [comment]
Okay, I will try and see, thank you so much for your kind help.

**Comment by mahmouddaif** [comment]
I tried to manually update libsane to 1.0.31 by installing deb package, but I ran into a lot of dependency issues, do you know a better way to do so?

**Comment by Ordissimo** [comment]
You have 2 choices!
1 - upgrade to bulleyes, which has natively libsane 1.0.31
2 - Build the package :
```
sudo apt install devscripts
dget http://deb.debian.org/debian/pool/main/s/sane-backends/sane-backends_1.0.31-4.dsc
dpkg-source -x sane-backends_1.0.31-4.dsc
cd sane-backends-1.0.31/
sudo mk-build-deps -i # <= Install the dependencies
debuild -tc
sudo apt-get purge devscripts # <= unistall env dev
sudo apt autoremove # <= clean system
sudo dpkg -i ../libsane-common_*.deb ../libsane1_*.deb ../libsane_*.deb ../sane-utils_*.deb
```

**Comment by mahmouddaif** [comment]
Thank you so much, I will try this solution.

**Comment by mahmouddaif** [comment]
This actually works, really I can't thank you enough.
