### ISSUE TITLE
clearsign failed

### ISSUE THREAD

**Issue by LotekHeavy** [Ordissimo/scangearmp2#5]
When I'm running with "debuild -tc" I got an clearsign failed error, at the end of the process. What can I do? Ubuntu 16.04 LTS. Thanks for any help :-)

```
Finished running lintian.
Now signing changes and any dsc files...
 signfile scangearmp2_3.50-2ubuntu.artful.dsc thierry <thierry@thierry-ThinkPad>
gpg: '/home/marcel/.gnupg/secring.gpg' kann nicht geöffnet werden
gpg: keydb_search failed: Fehler beim Öffnen der Datei
gpg: »thierry <thierry@thierry-ThinkPad>« übersprungen: Fehler beim Öffnen der Datei
gpg: /tmp/debsign.20l2rbj4/scangearmp2_3.50-2ubuntu.artful.dsc: clearsign failed: Fehler beim Öffnen der Datei
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed
```

**Comment by Ordissimo** [comment]
Hi Marcel It's my signature that is expected. If you want to sign the package here is a tutorial: http://blog.jonliv.es/blog/2011/04/26/creating-your-own-signed-apt-repository-and-debian-packages/
You do not have to edit and you are not going to distribute the package, .you can ignore the error message. The package has been well built. ls ../scangearmp2*.deb
