### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by Uenoowl** [Ordissimo/scangearmp2#51]
Hi,
I am confused by the difference between this repository and others. What's the different between scangearmp2,  libmfp2-canon and libcanon-proprio-bin?
I noticed that the license of scangearmp2 is GPL with an EXCEPTION, and the EXCEPTION can be removed, which means scangearmp2 should not contains any non-free code because it can be redistributed whit pure GPL if I am right.
However,  libmfp2-canon said it with only free code, what does it means? Is libmfp2-canon separated from scangearmp2? But how can scangearmp2 contains non-free code since it can be redistributed whit pure GPL?
Thanks

**Comment by Ordissimo** [comment]
Hi @Uenoowl ,
The scangearmp2 version of my repository, contains 3 elements:
1- binary libraries where the source code is not provided (under Canon license), it lets us use and redistribute it, without the right to decompile it.
2 - the scangearmp2 GUI in GPL provided by Canon, I have extended these features and migrated it to GTK3.
3 - The code developed by Ordissimo, which is based on Canon's proprietary libraries. This code provides a backend to "sane".

**Comment by Ordissimo** [comment]
- libcanon-proprio-bin contains the proprietary libraries for Canon, I repackage them but do not make any modification on them.
This allows you to use them without having to install the whole GTK2 toolkit, this supposes that you install libmfp2-canon.
- libmfp2-canon is the part provided by Ordissimo, which is under GPL license and is a backend of the sane project

Finally, and to clear up any ambiguity, I am the developer of the company Ordissimo with no ties whatsoever to Canon.

**Comment by Uenoowl** [comment]
Thanks for your explanation!
