### ISSUE TITLE
pacman AUR package

### ISSUE THREAD

**Issue by pvanderlinden** [Ordissimo/scangearmp2#55]
Thanks for this software!

More a question then an issue: I created an AUR package for this github repository. If you want to take it over, just let me know ( https://aur.archlinux.org/packages/scangearmp2-sane-git )?

Small issue: you are missing one make dependency `intltool`

**Comment by Ordissimo** [comment]
I added the missing dependency.
You are better than me to maintain the ArchLinux package!
Thanks for your work!
