### ISSUE TITLE
dpkg-buildpackage -us -uc ##  ERROR

### ISSUE THREAD

**Issue by Cralphen** [Ordissimo/scangearmp2#58]
Hello,
I got this error (Debian 10) when I execute the command "dpkg-buildpackage -us -uc ## ":

dpkg-buildpackage: error: cannot open file debian/changelog: No such file or directory

Can you help me?
Thank you very much!
Regards

**Comment by Ordissimo** [comment]
Hi @Cralphen ,
Here is the [debian](https://github.com/Ordissimo/scangearmp2/tree/debian) folder
