### ISSUE TITLE
Xsane starts scanning and fails

### ISSUE THREAD

**Issue by zerthimon** [Ordissimo/scangearmp2#8]
Says: Error during read: Error during device I/O.
Somtimes I'm able to acquire preview, or scan at 75dpi other resolutions cause error.

Scanning works perfectly from the program scangearmp2 iself.

**Comment by Ordissimo** [comment]
I do not reproduce your bugs. Can you give me more information.
Your operating system.
Have you compile scangearmp2 or taken a prepared version.

**Comment by zerthimon** [comment]
I've found the problem: had to replace `pixma` with `canon_pixma` in /etc/sane.d/dll.conf

Now, however, another problem:
Looks like I cannot change default scan parameters, whatever settings I choose in Xsane.
At least, resolution and scan area don't work - I always get the same resolution and same scan area.

**Comment by Ordissimo** [comment]
You are right. The canon backend provides two resolutions. Document is the best resolution.
Image the lower resolution.
I decided to set the low resolution for the resol less than 100.
And put the high resolution for the higher resolves in the other cases.
